# Generated by Django 2.0.6 on 2018-06-21 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180621_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='Question_text',
        ),
    ]
